### PR TITLE
Add Issue Template configuration

### PR DESCRIPTION
**Pull request by HarshCasper**
# Pull Request Template

## Description

Added the Issue Configuration `config.yml` file to customize the Issue creation workflow. As @gmajan has enabled the discussions and we would like to shift some core topics like feedback, queries and suggestions over there, it would be great if we can highlight the same if a Contributor is opening a new Issue itself. 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

It has been tested on a sample repository. If a User creates a new Issue now, they will see an option to kickstart a new discussion or go through the Contribution guideline. 

## Additional Context (Please include any Screenshots/gifs if relevant)

I wanted to better understand if we need to have a similar update added on our `README.md` file as well, to highlight that we have a discussion tab. If yes, I will push commits to add the same on `README` as well. 

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [X] I have checked my code and corrected any misspellings
- [X] I have tagged the reviewers in a comment below incase my pull request is ready for a review
- [X] I have signed the commit message to agree to Developer Certificate of Origin (DCO) (to certify that you wrote or otherwise have the right to submit your contribution to the project.) by adding "--signoff" to my git commit command.

### CODE REVIEW

**Comment by aornugent** [comment]
Thanks Harsh - how does this interact with our existing issue templates? Do we need to remove some that we are now directing elsewhere?

**Comment by HarshCasper** [comment]
> Thanks Harsh - how does this interact with our existing issue templates? Do we need to remove some that we are now directing elsewhere?

We do not need to remove any of our Issue Templates right now. GitHub natively displays the Issue Templates like these: 

image

With the addition of an Issue Template `config.yml`, we will be able to display the `Discussions` tab enabled so that users can post their questions/queries over there, rather than cluttering the Issues page as of now. Also, Contributing Guidelines have been added so that the Users can follow up with the same before creating an Issue. Both of these would be displayed on the same `New Issue` page below the other options.

**Comment by aornugent** [comment]
Sounds good - is this ready to be merged?

**Comment by HarshCasper** [comment]
> Sounds good - is this ready to be merged?

Yes, it is. If any bug would be coming up, I would fix the same in my upcoming PRs.

**Pull request merged**
