### PR TITLE
Fix the README

### LINKED ISSUE #128: Broken link in readme
The FLINT link in the readme seems to give a 404. Needs to be updated to the correct link.

### PR DESCRIPTION
**Pull request by HarshCasper**
## Description

Fixed some typos and simplified some of the complex phrases. Also fixed the dead link highlighted by @sarthakkundra on the Issue #128 

Fixes #128 

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### CODE REVIEW

**Comment by HarshCasper** [comment]
cc: @aornugent @shubhamkarande13

**Comment by shubhamkarande13** [comment]
Looks perfect!

**Comment by HarshCasper** [comment]
> @shubhamkarande13 - do you have sufficient permission to merge this? We need more people taking maintainer roles if we plan to keep so many repositories.

@aornugent It would be great to have a Team on the GitHub organization where we can be added, with sufficient permissions to perform reviews and merges on the fly.

**Comment by aornugent** [comment]
Done. Let me know if and when you need access to different projects.

**Pull request merged**
